### ISSUE TITLE
$ sudo dnf install steam Ошибка: nothing provides libtxc_dxtn(x86-32) needed by steam-1.0.0.52-1.fc24.i686 

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/steam#1]
[Report](https://www.linux.org.ru/news/linux-general/12591529?cid=12595141) from our user:

```
$ sudo dnf install steam
Error: nothing provides libtxc_dxtn(x86-32) needed by steam-1.0.0.52-1.fc24.i686 
```

@sergiomb2

**Comment by sergiomb2** [comment]
ya thanks for the report , as workaround (is what I have) 

`dnf install http://download1.rpmfusion.org/free/fedora/updates/testing/23/x86_64/libtxc_dxtn-1.0.1-1.gitef072983.fc23.i686.rpm`

**Comment by paulcarroty** [comment]
[Fixed](https://github.com/UnitedRPMs/libtxc_dxtn).

**Comment by sergiomb2** [comment]
thanks
